server:
  port: 8000

spring:
  application:
    name: api-gateway-service
  config:
    activate:
      on-profile: simple

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka