server:
  port: 8001

spring:
  application:
    name: api-gateway-service
  config:
    activate:
      on-profile: user-service
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true  # 서비스 이름을 소문자로 변환하여 찾음
          enabled: true
      routes:
        - id: user-service
        - uri: lb://USER-SERVICE
        - predicates:
          - Path=/user-service/**
        - id: first-service
          uri: lb://MY-FIRST-SERVICE
          predicates:
            - Path=/first-service/**
        - id: second-service
          uri: lb://MY-SECOND-SERVICE
          predicates:
            - Path=/second-service/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
