version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: my-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=1000
    networks:
      - kafka-network

  adminer:
    image: adminer:latest
    container_name: my-adminer
    restart: always
    ports:
      - "9090:8080"
    depends_on:
      - mariadb
    networks:
      - kafka-network

volumes:
  mariadb_data:

networks:
  kafka-network:
    name: kafka-network
    driver: bridge